[package]
description = "Parser/encoder for ASN.1 BER/DER data"
license = "MIT/Apache-2.0"
keywords = ["BER","DER","ASN1","parser","nom"]
homepage = "https://github.com/rusticata/der-parser"
repository = "https://github.com/rusticata/der-parser.git"
name = "asn1-rs"
version = "0.1.0"
authors = ["Pierre Chifflier <chifflier@wzdftpd.net>"]
categories = ["parser-implementations"]
# readme = "README.md"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
bigint = ["num-bigint"]
datetime = ["chrono"]
serialize = ["cookie-factory"]

[dependencies]
chrono = {version="0.4.19", optional=true }
cookie-factory = { version="0.3.0", optional=true }
nom = "6.1.2"
num-bigint = { version = "0.4", optional = true }
num-traits = "0.2.14"
rusticata-macros = "3.0.1"
thiserror = "1.0.25"

[dev-dependencies]
colored = "2.0"
hex-literal = "0.3.1"
oid-registry = { version="0.1.3", features=["crypto","x509"] }
pem = "0.8.3"

[patch.crates-io]
oid-registry = { path="../../oid-registry" }
